
version: 0.2
env:
  parameter-store:
    # These are used in common/config/rush/.npmrc[-publish]
    GITHUB_PACKAGE_REGISTRY: /github/registry
    GITHUB_PERSONAL_ACCESS_TOKEN: /github/mpiroc-org/ci
    GITHUB_SCOPE: /github/mpiroc-org/scope
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - node common/scripts/install-run-rush.js update
  build:
    commands:
      - node common/scripts/install-run-rush.js build
      - node common/scripts/install-run-rush.js lint
  post_build:
    commands:
      - node common/scripts/install-run-rush.js test
      - |
        if [ $CODEBUILD_WEBHOOK_TRIGGER = "branch/master" ]; then
          node common/scripts/install-run-rush.js publish --include-all --publish --add-commit-details --apply --registry https://npm.pkg.github.com/$GITHUB_SCOPE
        fi
